permesso_admin: "taser.admin"
logs_enabled: true # attiva o disabilita i logs delle azioni del taser (true / false)

taser:
  cariche_massime: 3
  suono_ricarica: "minecraft:reloadshotgun"
  suono_taser: "minecraft:block.anvil.place"
  nome: "&fTaser"
  item: "STICK"
  cmdata: 163
  lore:
    - "&7Cariche: %current%/%max%"

ricariche:
  nome: "&fRicarica Taser"
  item: "PHANTOM_MEMBRANE"
  cmdata: 10
  lore:
    - "&7Utilizzabile per ricaricare un taser"
